library(dplyr)
library(reshape2)
library(lubridate)

Data <- read.csv("./Data/household_power_consumption.txt", sep = ';', stringsAsFactors = FALSE)
DataPlot <- filter(Data, Data$Date == "1/2/2007" | Data$Date == "2/2/2007")
DataPlot <- mutate(DataPlot, GAP = as.numeric(DataPlot$Global_active_power))
DataPlot <- mutate(DataPlot, DateFull = paste(DataPlot$Date," ",DataPlot$Time))
DataPlot <- mutate(DataPlot, Fecha = dmy_hms(DataPlot$DateFull))
DataPlot <- mutate(DataPlot, SM1 = as.numeric(DataPlot$Sub_metering_1))
DataPlot <- mutate(DataPlot, SM2 = as.numeric(DataPlot$Sub_metering_2))
DataPlot <- mutate(DataPlot, SM3 = as.numeric(DataPlot$Sub_metering_3))
DataPlot <- mutate(DataPlot, GRP = as.numeric(DataPlot$Global_reactive_power))
DataPlot <- mutate(DataPlot, V = as.numeric(DataPlot$Voltage))

png(filename = "plot4.png", width = 480, height = 480, units = "px", pointsize = 12, bg = "white")
par(mfcol = c(2, 2))
plot(DataPlot$Fecha, DataPlot$GAP, type = "l", xlab = "", ylab = "Global Active Power (kilowatts)")
plot(DataPlot$Fecha, DataPlot$SM1, type = "l", col = "gray30", xlab = "", ylab = "Energy sub metering")
points(DataPlot$Fecha, DataPlot$SM2, type = "l", col = "red")
points(DataPlot$Fecha, DataPlot$SM3, type = "l", col = "blue")
legend("topright", col = c("gray30","red","blue"), legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), lty = 1)
plot(DataPlot$Fecha, DataPlot$V, type = "l", xlab = "datetime", ylab = "Voltage")
plot(DataPlot$Fecha, DataPlot$GRP, type = "l", xlab = "datetime", ylab = "Global_reactive_power")
dev.off()